import argparse
import json
from pathlib import Path
from collections import defaultdict
import numpy as np
from PIL import Image
import math
import csv

def iou(boxA, boxB):
    # boxes: [x1,y1,x2,y2]
    xa1, ya1, xa2, ya2 = boxA
    xb1, yb1, xb2, yb2 = boxB
    interx1 = max(xa1, xb1)
    intery1 = max(ya1, yb1)
    interx2 = min(xa2, xb2)
    intery2 = min(ya2, yb2)
    interw = max(0.0, interx2 - interx1)
    interh = max(0.0, intery2 - intery1)
    inter = interw * interh
    areaA = max(0.0, xa2 - xa1) * max(0.0, ya2 - ya1)
    areaB = max(0.0, xb2 - xb1) * max(0.0, yb2 - yb1)
    union = areaA + areaB - inter
    return inter / union if union > 0 else 0.0


def load_gt_for_image(label_path: Path, img_w: int, img_h: int):
    boxes = []
    if not label_path.exists():
        return boxes
    text = label_path.read_text(encoding='utf-8').strip()
    if not text:
        return boxes
    for line in text.splitlines():
        parts = line.strip().split()
        if not parts:
            continue
        cls = int(float(parts[0]))
        # YOLO normalized x_center y_center w h
        try:
            xc, yc, w, h = map(float, parts[1:5])
        except Exception:
            continue
        x1 = (xc - w/2.0) * img_w
        y1 = (yc - h/2.0) * img_h
        x2 = (xc + w/2.0) * img_w
        y2 = (yc + h/2.0) * img_h
        boxes.append({'class': cls, 'xyxy': [x1, y1, x2, y2]})
    return boxes


def normalize_pred(pred_xyxy, img_w, img_h):
    # If coordinates appear normalized (<=1), convert to pixels
    if all(0.0 <= v <= 1.0 for v in pred_xyxy):
        xc1 = pred_xyxy[0] * img_w
        yc1 = pred_xyxy[1] * img_h
        xc2 = pred_xyxy[2] * img_w
        yc2 = pred_xyxy[3] * img_h
        return [xc1, yc1, xc2, yc2]
    return pred_xyxy


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--preds', required=True, help='predictions JSON generated by val_with_yolo.py')
    parser.add_argument('--labels', required=True, help='path to val labels directory (YOLO txts)')
    parser.add_argument('--out', required=True, help='output prefix (png/csv)')
    parser.add_argument('--iou-thres', type=float, default=0.5)
    args = parser.parse_args()

    preds_path = Path(args.preds)
    labels_dir = Path(args.labels)
    out_prefix = Path(args.out)

    preds = json.loads(preds_path.read_text(encoding='utf-8'))

    # map image -> preds
    img_to_preds = {}
    for item in preds:
        img_to_preds[str(Path(item.get('image')).name)] = item.get('preds', [])

    # collect classes from labels
    classes = set()
    for p in labels_dir.glob('*.txt'):
        txt = p.read_text(encoding='utf-8').strip()
        if not txt:
            continue
        for line in txt.splitlines():
            parts = line.strip().split()
            if parts:
                classes.add(int(float(parts[0])))
    if not classes and preds:
        for item in preds:
            for pr in item.get('preds', []):
                classes.add(int(pr.get('class')))
    classes = sorted(list(classes))
    if not classes:
        print('No classes found in labels or predictions')
        return
    cls_to_idx = {c: i for i, c in enumerate(classes)}
    C = len(classes)

    # confusion counts matrix: rows GT, cols pred
    matrix = np.zeros((C, C), dtype=int)
    tp = [0] * C
    fp = [0] * C
    fn = [0] * C

    # iterate over images in preds list
    for item in preds:
        img_path = Path(item.get('image'))
        img_name = img_path.name
        # attempt to open image to get size
        try:
            im = Image.open(img_path)
            w, h = im.size
        except Exception:
            # try to infer image path from labels dir name
            # if not found, skip
            # find corresponding label file
            label_file = labels_dir / (img_name.rsplit('.', 1)[0] + '.txt')
            # try to guess image size from reading label is not possible
            # skip if image not accessible
            print('Warning: cannot open image', img_path, '— ensure script runs from project root or pass absolute paths')
            continue

        gt_boxes = load_gt_for_image(labels_dir / (img_name.rsplit('.', 1)[0] + '.txt'), w, h)
        preds_list = item.get('preds', [])
        # normalize pred coords
        for p in preds_list:
            if 'xyxy' in p:
                p['xyxy'] = normalize_pred(p['xyxy'], w, h)

        # matching: greedy by highest IoU
        matched_gt = set()
        matched_pred = set()
        iou_records = []
        for pi, p in enumerate(preds_list):
            for gi, g in enumerate(gt_boxes):
                i = iou(p['xyxy'], g['xyxy'])
                if i >= args.iou_thres:
                    iou_records.append((i, gi, pi))
        iou_records.sort(reverse=True, key=lambda x: x[0])
        for iou_val, gi, pi in iou_records:
            if gi in matched_gt or pi in matched_pred:
                continue
            gcls = gt_boxes[gi]['class']
            pcls = int(preds_list[pi].get('class'))
            gi_idx = cls_to_idx.get(gcls)
            pi_idx = cls_to_idx.get(pcls)
            if gi_idx is None or pi_idx is None:
                continue
            matrix[gi_idx, pi_idx] += 1
            if gi_idx == pi_idx:
                tp[gi_idx] += 1
            else:
                # misclassification counts as FP for pred class and FN for GT class
                fp[pi_idx] += 1
                fn[gi_idx] += 1
            matched_gt.add(gi)
            matched_pred.add(pi)

        # unmatched preds -> FP
        for pi, p in enumerate(preds_list):
            if pi in matched_pred:
                continue
            pcls = int(p.get('class'))
            pi_idx = cls_to_idx.get(pcls)
            if pi_idx is not None:
                fp[pi_idx] += 1

        # unmatched gts -> FN
        for gi, g in enumerate(gt_boxes):
            if gi in matched_gt:
                continue
            gcls = g['class']
            gi_idx = cls_to_idx.get(gcls)
            if gi_idx is not None:
                fn[gi_idx] += 1

    # write CSV for matrix
    csv_path = out_prefix.with_suffix('.csv')
    with open(csv_path, 'w', newline='', encoding='utf-8') as fh:
        writer = csv.writer(fh)
        header = ['GT\\Pred'] + [str(c) for c in classes]
        writer.writerow(header)
        for i, c in enumerate(classes):
            row = [str(c)] + matrix[i].tolist()
            writer.writerow(row)

    # write summary JSON
    summary = {
        'classes': classes,
        'matrix_csv': str(csv_path),
        'tp': {str(c): int(tp[idx]) for idx, c in enumerate(classes)},
        'fp': {str(c): int(fp[idx]) for idx, c in enumerate(classes)},
        'fn': {str(c): int(fn[idx]) for idx, c in enumerate(classes)},
    }
    json_path = out_prefix.with_suffix('.json')
    with open(json_path, 'w', encoding='utf-8') as fh:
        json.dump(summary, fh, ensure_ascii=False, indent=2)

    print('Wrote confusion CSV to', csv_path)
    print('Wrote summary JSON to', json_path)


if __name__ == '__main__':
    import json
    main()
